### ISSUE TITLE
How to get total screen time of iOS device?

### ISSUE THREAD

**Issue by karimApps142** [Kingstinct/react-native-device-activity#8]
Hi there,

I'm trying to find a way to get the total screen time of an iOS device using the react-native-device-activity library. I've looked through the documentation and examples, but I'm not sure how to accomplish this task.

**Comment by robertherber** [comment]
@karimApps142 The API is not designed this way by Apple. You'd need to register and listen to events like `5_minutes_reached`, `10_minutes_reached` to achieve this.
