### ISSUE TITLE
Possible Unhandled Promise Rejection (id: 0)

### ISSUE THREAD

**Issue by karimApps142** [kingstinct/react-native-device-activity#9]
I am using the react-native-device-activity library to request authorization for the device's activity data with     ReactNativeDeviceActivity.requestAuthorization()
, but I am receiving the error message "Possible Unhandled Promise Rejection (id: 0): Error: Couldn’t communicate with a helper application." when attempting to request authorization.

Steps to Reproduce
1. Install and link the react-native-device-activity library.
2. Request authorization for the device's activity data using the requestAuthorization() function provided by the library.
3. Wait for the permission response.

Environment
React Native version: 0.72.3
Platform: iPhone 8 Plus real device

**Comment by tarasfo** [comment]
@karimApps142 how did you resolve this issue?

**Comment by kamil6311** [comment]
Hello I have the same exact issue, using a real iPhone
